import fs from "node:fs/promises";
import path from "node:path";

// Where managed file bytes live (spec 5.1: object storage or a
// filesystem-backed adapter, with metadata in the database). 0.1.0 ships
// the filesystem adapter for both engines; an S3-compatible adapter for
// the cloud comes with the first cloud deployment.
export interface FileStore {
  put(key: string, bytes: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
}

export function filesystemStore(root: string): FileStore {
  const resolve = (key: string) => {
    // Keys are generated by the server (tenant/attachment IDs); refuse
    // anything that could escape the storage folder anyway.
    if (!/^[0-9a-f-]+\/[0-9a-f-]+$/i.test(key)) throw new Error(`Invalid storage key: ${key}`);
    return path.join(root, key);
  };
  return {
    async put(key, bytes) {
      const file = resolve(key);
      await fs.mkdir(path.dirname(file), { recursive: true });
      // Write to a temporary name, then rename: a crash never leaves a
      // half-written file under the real name.
      const tmp = `${file}.${process.pid}.tmp`;
      await fs.writeFile(tmp, bytes);
      await fs.rename(tmp, file);
    },
    async get(key) {
      return fs.readFile(resolve(key));
    },
  };
}

// Image types accepted for product photos, recognized by their first bytes
// rather than the file name (spec 13: validate by content).
export function sniffImage(bytes: Buffer): "image/jpeg" | "image/png" | "image/webp" | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg";
  if (bytes.length >= 8 && bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])))
    return "image/png";
  if (bytes.length >= 12 && bytes.toString("ascii", 0, 4) === "RIFF" && bytes.toString("ascii", 8, 12) === "WEBP")
    return "image/webp";
  return null;
}

export const MAX_PHOTO_BYTES = 10 * 1024 * 1024;
